export const actionTypes = Object.freeze({
  ALL_PRODUCTS_REQUEST: "ALL_PRODUCTS_REQUEST",
  ALL_PRODUCTS_SUCCESS: "ALL_PRODUCTS_SUCCESS",
  ALL_PRODUCTS_FAIL: "ALL_PRODUCTS_FAIL",

  CURRENT_USER: "CURRENT_USER",

  DETAILS_PRODUCTS_REQUEST: "DETAILS_PRODUCTS_REQUEST",
  DETAILS_PRODUCTS_SUCCESS: "DETAILS_PRODUCTS_SUCCESS",
  DETAILS_PRODUCTS_FAIL: "DETAILS_PRODUCTS_FAIL",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",

  LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAIL: "LOGOUT_USER_FAIL",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  SEND_MAIL_FORGOT_PASSWORD: "SEND_MAIL_FORGOT_PASSWORD",

  UPDATE_NEW_PASSWORD: "UPDATE_NEW_PASSWORD",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",

  SHIPPING_INFO: "SHIPPING_INFO",

  CREATE_ORDER: "CREATE_ORDER",

  MY_ORDER: "MY_ORDER",

  CREATE_REVIEW: "CREATE_REVIEW",

  ADMIN_ALL_PRODUCTS: "ADMIN_ALL_PRODUCTS",

  CREATE_NEW_PRODUCT: "CREATE_NEW_PRODUCT",

  DELETE_PRODUCT: "DELETE_PRODUCT",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  CLEAR_STATE: "CLEAR_STATE",

  ALL_ORDERS: "ALL_ORDERS",
  UPDATE_ORDERS: "UPDATE_ORDERS",
  SINGLE_ORDERS: "SINGLE_ORDERS",
  DELETE_ORDERS: "DELETE_ORDERS",

  ALL_USERS: "ALL_USERS",
  UPDATE_USER_ADMIN: "UPDATE_USER_ADMIN",
  GET_SINGLE_USER_ADMIN: "GET_SINGLE_USER_ADMIN",
  DELETE_USER_ADMIN: "DELETE_USER_ADMIN",
});
